name: autosurvey
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - spacy
  - cupy
  - scikit-learn
  - pandas
  - gensim
  - matplotlib
  - nltk
  - pip:
    - arxiv==0.5.3
    - pdfminer-six
    - rouge-score
